FROM golang:alpine

LABEL maintainer=austinjalexander@nicewrk.com

RUN apk add --update --no-cache make git
RUN go get -u github.com/alecthomas/gometalinter
RUN gometalinter --install

WORKDIR /go/src/github.com/nicewrk/design-brain-api
COPY . .

RUN make

CMD ["make", "test"]
